# Site live URL
url: Upbeat-D/Upbeat-D.Github.io
title: Ming Tang | Peking University | Personal Website

# Harmony theme configuration. Please change accordingly.
harmony:
    name: Ming Tang | Peking University | Personal Website
    # Little description about your site
​    description: Understanding Earth Through Chemistry
    # 'meta_description:' Write an awesome description for your new site here.
    # It will appear in your document head meta (for Google search results) and
    # in your feed.xml site description.
​    meta_description: Ming Tang - Understanding Earth Through Chemistry | Peking University, School of Earth and Space Sciences
​    basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
    # Google Analytics key, leave blank to ignore
​    google_analytics_key: G-3JFCV2K7PR
​    show_disclaimer: false

# Conversion / Build settings
markdown: kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
    - CNAME
    - Gemfile
    - Rakefile
    - README.md
    - .gitignore
    - .sass-cache
    - Gemfile.lock
    - vendor

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed

# for jekyll-seo-tag
author: Ming Tang

plugins:
    - jekyll-feed
        - jekyll-seo-tag
        - jekyll-tidy
        - jekyll-sitemap
